[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"


[build.environment]
# Pin major only so the image picks a valid 20.x
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client", "prisma"]
included_files = [
  "node_modules/.prisma/**",
  "node_modules/@prisma/client/**"
]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200