# netlify.toml (clean)

[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  # Pin major only so the image picks a valid 20.x
  NODE_VERSION = "20"

# Single [functions] table — set global bundler once
[functions]
  node_bundler = "esbuild"

# Default: keep functions lean (no Prisma by default)
[functions."*"]
  external_node_modules = []
  included_files = []

# DB-backed functions ONLY (include Prisma client + engines)
[functions."process-upload-background"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]  # engines only

[functions."auth"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[functions."logout"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[functions."admin-download-master"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[functions."admin-master-record"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[functions."admin-jobs"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[functions."jobs"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[functions."download"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

  [functions."me"]
  external_node_modules = ["@prisma/client","prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[[edge_functions]]
function = "auth-protect"
path = "/dashboard"

[[edge_functions]]
function = "auth-protect"
path = "/dashboard/*"

[[edge_functions]]
function = "auth-protect"
path = "/app/*"

[[redirects]]
  from = "/admin-llm-cache"
  to   = "/.netlify/functions/admin-llm-cache"
  status = 200

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200