[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"


[build.environment]
# Pin major only so the image picks a valid 20.x
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client", "prisma"]
included_files = [
"node_modules/.prisma/**"
]

[[redirects]]
from = "/api/*"
status = 200
force = true
to = "/.netlify/functions/:splat"


[[redirects]]
from = "/*"
status = 200
to = "/index.html"