[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"


[build.environment]
# Pin major only so the image picks a valid 20.x
NODE_VERSION = "20"


# IMPORTANT: ensure there are **no** Next.js plugins below.
# Remove any [[plugins]] blocks like `@netlify/plugin-nextjs`.


[[redirects]]
from = "/api/*"
status = 200
force = true
to = "/.netlify/functions/:splat"


[[redirects]]
from = "/*"
status = 200
to = "/index.html"