[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

  [build.environment]
NODE_VERSION = "20.14.0"   # any 20.x LTS is fine

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200